### ISSUE TITLE
Stars don't look aligned in a row

### ISSUE THREAD

**Issue by netnaps** [billerickson/BE-Comment-Rating#2]
hi, 

I installed this but I could not see the stars in a row, 
have deactivated temporarily may be the CSS needs a correction.

Thanks
![Screenshot 2020-07-22 at 6 30 38 PM](https://user-images.githubusercontent.com/67054369/88179521-b041c280-cc49-11ea-8327-01137ae20728.png)

**Comment by netnaps** [comment]
Using standard AMP Mode

**Comment by billerickson** [comment]
Can you send me a link to a page that has the issue? My guess is your theme's CSS is overriding the CSS in the plugin and making them display stacked like that.

The plugin has them set to `display: inline-block;` ([see here](https://github.com/billerickson/BE-Comment-Rating/blob/master/be-comment-rating.css#L18)) but it's likely your theme has styles for labels in the comment form that is more specific than `.be-comment-rating > label`

**Comment by netnaps** [comment]
Hi, the same was tested on localhost, I will recheck the same again with my theme and update a URL once the site is live.

Thanks for your reply.
