### ISSUE TITLE
How to add? 

### ISSUE THREAD

**Issue by girgismena** [billerickson/BE-Comment-Rating#3]
Hello!! 
How can I add it to my WordPress site while it's not zip files? 
Sorry but I never add similar plugins and I'm a beginner with AMP !!

**Comment by billerickson** [comment]
Two ways you can add it to your size:

1. [Download the zip](https://github.com/billerickson/BE-Comment-Rating/archive/refs/heads/master.zip). On your website, go to Plugins > Add new > Upload Plugin, and upload the zip, then click "Activate".

OR

2. [Download the zip](https://github.com/billerickson/BE-Comment-Rating/archive/refs/heads/master.zip) and unzip it on your computer. Using FTP or SFTP details provided by your host, upload the unzipped folder into /wp-content/plugins/.  On your website, go to Plugins and click "Activate".

**Comment by girgismena** [comment]
Thanks a lot bro and it's amazing work.
