### ISSUE TITLE
start dosent show

### ISSUE THREAD

**Issue by girgismena** [billerickson/BE-Comment-Rating#4]
Hello 
after i asked the last issue : 
https://github.com/billerickson/BE-Comment-Rating/issues/3
i installed the plugin and activated it and i added the filters in my functions.php 
still my comment field without the starts .
![1](https://user-images.githubusercontent.com/47543883/161961564-8716f3be-5fed-4aff-b189-8c054a3e495f.jpg)
![2](https://user-images.githubusercontent.com/47543883/161961565-0346f191-d0b4-4467-bbe2-e407eeb7ec1d.jpg)

can yo explain more please ?

**Comment by girgismena** [comment]
Hello again 
its my bad ...
its show on posts ony not on pages and i dint know why and can we make it show on pages comments field too or not ?
and by the was it show vertically too as the old issue was here ...
https://github.com/billerickson/BE-Comment-Rating/issues/2
i loved your basic system and thats why i try to work with .

**Comment by billerickson** [comment]
You can control which post types it appears on using the `be_comment_rating_post_types` filter. [See the code here](https://github.com/billerickson/BE-Comment-Rating/blob/master/be-comment-rating.php#L125-L130).

To add support to pages, add this to your theme's functions.php file:

```
add_filter(
	'be_comment_rating_post_types',
	function( $post_types ) {
		$post_types[] = 'page';
		return $post_types;
	}
);
```
